# -*- coding: utf-8 -*-
"""0628 과제

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgMTJsRw0NYHGNJp1VaGAONjlEebWFBk

**1**
"""

# 1330번
# map 함수를 이해하고 있는가?
# if else 조건문을 사용할 수 있는가?
A,B = map(int,input().split()) # int로 감싸주면 안되는 이유 A,B = int(input().split())
if A>B:                        # ex) 위 식에 2 4를 입력하면 컴퓨터가 "2 4"로 생각해서
    print(">")                 # 공백을 int 형태로 바꿔줄 수 없기 때문에
elif A<B:                      # "각각" 적용해줄 수 있는 map을 사용하는 것임!
    print("<")
else:
    print("==")

"""**2**"""

# 9498번
# elif 조건문을 사용할 수 있는가?
score = int(input())
if 90 <= score <= 100:
  print("A")
elif 80 <= score < 90:
  print("B")
elif 70 <= score < 80:
  print("C")
elif 60 <= score < 70:
  print("D")
else:
  print("F")

"""**3**

"""

# 2754번
Luna_year = int(input())
if Luna_year % 4 == 0 and Luna_year % 100 != 0 or Luna_year % 400 == 0:
  print("1")
else:
  print("0")

"""**4**"""

#14681번
x = int(input())
y = int(input())
if x > 0 and y > 0 :
  print("1")
elif x < 0 and y >0 : #if elif 모두 사용가능
  print("2")
elif x < 0 and y < 0 :
  print("3")
elif x > 0 and y < 0 :
  print("4")

"""**5**"""

H,M = map(int,input().split())
if H == 0 and M < 45 :
  print(23,60+M-45)
elif H == 0 and M >= 45 :
  print(0,M-45)
elif 1 <= H < 24 and M < 45 :
  print(H-1,60+M-45)
elif 1 <= H < 24 and M >= 45 :
  print(H,M-45)

"""**6**"""

#2525번
A,B = map(int,input().split())
# 기본원칙: B+C의 값이 60을 넘어가면 출력할 A값이 변화한다.
C = int(input())
if B + C < 60 : # B + C가 60을 넘지 않으므로 입력된 A값에 변화없음
  print(A, B + C)
if 7 <= A and B + C >= 60 :
  print(A+((B+C)//60),60-(B + C))
elif 7 <= A and B + C < 60 :
  print(A,B + C)
elif A > 7 and B + C < 60 :
  print(A + ((B + C)//60))

"""**6-1**

"""

#2525번 #수정
A,B = map(int,input().split())
C = int(input())

A = A + C // 60  # A,B값을 먼저 정의해준다.
B = B + C % 60   # C가 if문 내에서 해결되려고 하면 복잡해질 것 같아서
                 # 앞부분에서 정의내려 처리
if B >= 60:
  A = A + 1
  B = B - 60
if A >= 24:
  A = A - 24
print(A,B)

"""**7**"""

map(int, input().split())

"""**For문/While문**

**1**
"""

#2739번
N = int(input())
for x in range(1, 10):
    print(N,"*",x,"=",x*N)

"""**2**"""

T = int(input())
for _ in range(T):
    A,B = map(int, input().split())
    print(A+B)