# -*- coding: utf-8 -*-
"""청년취업사관학교 강북캠퍼스 Huggingface 1일차

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NChjAaXVLsN1dg5zGfzC0yxMHiaZHNaw

**1**
"""

print("Hello World!")

"""**2**"""

A,B = input().split() # 특정값을 넣겠다는 선언이 input()함수이고, .은 메서드를 호출하기 위해서
print(int(A)+int(B)) # int(A+B)가 안되는 이유는?

"""**3**"""

A,B = input().split()
print(int(A)-int(B))

"""**4**"""

A,B = input().split()
print(int(A)*int(B))

"""**5**"""

A,B = input().split()
print(int(A)/int(B))

"""**6**"""

A,B = input().split()
print(int(A)+int(B))
print(int(A)-int(B))
print(int(A)*int(B))
print(int(A)//int(B))
print(int(A)%int(B))

"""**7**"""

A = input()
print(A+"??!") # 왜 A가 ""안에 들어가면 안되는걸까?

"""**8**"""

Bulgi = int(input()) # A로 입력하면 알아보기 힘들다고해서 확인 쉬운 네이밍 적용
print(Bulgi-543)

"""**9**"""

A,B,C = map(int,input().split()) #map함수 사용시 왜 int, 로 변하는지?
print((A+B)%C)
print(((A%C) + (B%C))%C)
print((A*B)%C)
print(((A%C) * (B%C))%C)

"""**10**"""

a,b = int,input().split() # 작동안하는 이유를 알 수 없음.. 여기선 되는데? #백준 문제양식 맞지 않았음(0628피어세션)
print(a*(b%10))
print(a*(int((b%100)//10)))
print(a*(int(b//100)))
print(a*b)

"""**11**"""

a,b,c = input().split()
print(int(a)+int(b)+int(c))

"""**12**"""

print("    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \\(__)|")

"""**13**"""

print("|\_/|") #따옴표 출력 위해 앞에 백슬래시 \"
print("|q p|   /}")
print("( 0 )\"\"\"\\")
print("|\"^\"`   |")
print("||_/=\\\\__|")